[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    bodmer/TFT_eSPI
    bitbank2/AnimatedGIF
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git

build_flags =
    -DTFT_WIDTH=320
    -DTFT_HEIGHT=240
    -DTOUCH_CS=33
    -DLOAD_GLCD
    -DLOAD_FONT2
    -DLOAD_FONT4
    -DLOAD_FONT6
    -DSPI_FREQUENCY=40000000
    -include include/User_Setup.h
    -DUSER_SETUP_LOADED
    
    